apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: simple-app
spec: 
  destination: 
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: examples/1-simple-app
    repoURL: https://github.com/MaxCloud101/curso-de-CAPA-example.git
    targetRevision: HEAD
